### PR TITLE
Fixes multiple compilation issues.

### PR DESCRIPTION
**Pull request by Bidski**
Reopened PR based on 01org/caffe#89

### CODE REVIEW

**Comment by Bidski** [comment]
> @Bidski OK, please create a new one. You are right. The situation here is that the user already specify to use OpenBLAS. But the system has a cblas.h in /usr/include and the /usr/include is in the include directories. Thus #include <cblas.h> will include that file rather than the /usr/include/openblas/cblas.h, then latter, the two inline functions have been removed by your patch and the compiler will complain can't find those two functions.

Since this is a cmake based project the user should be able to force cmake to use the correct includes/libraries in this situation

**Comment by gongzg** [comment]
@Bidski Not really. It just breaks the build on my system :(. The reason is that the /usr/include is in the include directories and there is a cblas.h. I just pushed a patch to fix that.

**Comment by Bidski** [comment]
@gongzg Your patch breaks the build on my system as `openblas/cblas.h` does not exist.

**Comment by gongzg** [comment]
oh :(. That's a problem, we may need to do something in the cmake stage to find the correct header file. what's your opinion.

**Comment by gongzg** [comment]
@Bidski I prefer to revert my last patch and then use OPENBLAS_VERSION to determine whether we should enable those two inline-function to make sure we don't break the build anyway.

**Comment by gongzg** [comment]
@Bidski just pushed a fix. Please check whether it works for you.

**Comment by Bidski** [comment]
That fix fixes the build for me.

Just as an afterthought, it would probably be a good idea to conditionally allow the compilation of the `tools` in the same way that I did for the `examples`. This should allow for only building the caffe library without any examples, tools, or tests.

**Pull request merged**
