### PR TITLE
Fix a small bug that cv::retangle's fisrt parameter can't receive a const&

### PR DESCRIPTION
**Pull request by listenlink**
@gongzg This patch fix a compilation bug when calling cv:retangle function with a const & image for first parameter.

### CODE REVIEW

**Comment by gongzg** [comment]
This may not be the best fix for this issue. By default ShowResult should not modify the original image. We may need to modify the show result's implementation.

**Comment by listenlink** [comment]
@gongzg modify the patch to use const_cast instead to fix the compiling errors. I am not sure if you mean we should copy the original Mat to do the show_result work?

**Comment by gongzg** [comment]
It's better to clone the image rather than modify the original image in the show_result function. One possible scenario is as below:
create_image()
for() {
  forward(img)
  show_result(img)
}
We may use the above style of code to iterate the inference on one or multiple images for several times.
If the show_result will change the original image, it will bring issues after some loops.

**Comment by listenlink** [comment]
Got your meaning. Have modified into clone method.

**Pull request merged**
